-- Tag where a CustomFood row came from. "USER" = manually entered via the
-- custom-food dialog. "AI" = generated by the AI fallback (Gemini + Google
-- search) and persisted when the user tapped the AI result card. AI rows
-- get a "Sparkles · AI estimate" badge in search so users sanity-check.

CREATE TYPE "CustomFoodSource" AS ENUM ('USER', 'AI');

ALTER TABLE "CustomFood"
  ADD COLUMN "source"    "CustomFoodSource" NOT NULL DEFAULT 'USER',
  ADD COLUMN "aiModel"   TEXT,
  ADD COLUMN "aiSources" TEXT[] NOT NULL DEFAULT '{}';
