import type { MetadataRoute } from "next";

// PWA manifest — served at /manifest.webmanifest. Used by browsers to:
//  • Register the site as installable (Android Chrome shows the native
//    "Install app" prompt when the user spends ~30s on the site).
//  • Render the app from the home-screen in standalone mode (no URL bar)
//    on both Android and iOS.
//  • Colour the OS chrome (status bar, splash) with the brand gradient
//    base. Icons live next to this file as `icon.tsx` and `apple-icon.tsx`
//    — Next.js auto-includes them in the manifest.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "kcals — calorie tracker",
    short_name: "kcals",
    description:
      "Track meals, hit your goals, share progress with the people you eat with.",
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#0a0a0a",
    theme_color: "#10b981",
    categories: ["health", "fitness", "food", "lifestyle"],
    icons: [
      {
        // Generated by app/icon.tsx — fills the frame, for contexts that
        // don't mask (favicon, "any" purpose).
        src: "/icon",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        // Generated by app/icon-maskable/route.tsx — flame kept inside the
        // safe zone so Android's icon mask + splash screen look native.
        src: "/icon-maskable",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
    // Screenshots unlock Android's richer install dialog (an app card with a
    // preview). Generated by the /screenshot-* routes.
    screenshots: [
      {
        src: "/screenshot-narrow",
        sizes: "1080x1920",
        type: "image/png",
        form_factor: "narrow",
        label: "kcals — your daily calorie dashboard",
      },
      {
        src: "/screenshot-wide",
        sizes: "1920x1080",
        type: "image/png",
        form_factor: "wide",
        label: "kcals — your daily calorie dashboard",
      },
    ],
  };
}
